SELECT DATE_FORMAT(DATETIME, '%H') HOUR, COUNT(*) COUNT
FROM ANIMAL_OUTS
GROUP BY 1
HAVING CAST(HOUR AS UNSIGNED) >= 9 AND CAST(HOUR AS UNSIGNED) < 20
ORDER BY 1;

-- 입양 시각이 9시부터 19시까지인 동물들의 입양 시각과 개수 출력하기
